# Generated by Django 6.0.2 on 2026-02-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_subscriptionplan_subscription_paymenthistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
    ]
