# Generated by Django 6.0.2 on 2026-03-03 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_paymenthistory_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='users.subscription'),
        ),
    ]
