# Generated by Django 6.0.2 on 2026-03-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_parental_controls'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age_restriction',
            field=models.BooleanField(default=False),
        ),
    ]
