# Generated by Django 6.0.2 on 2026-03-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age_restriction',
        ),
        migrations.AddField(
            model_name='profile',
            name='maturity_level',
            field=models.CharField(choices=[('KIDS', 'Kids'), ('ADULT', 'Adult')], default='ADULT', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_profile_name_per_user'),
        ),
    ]
