# Generated by Django 6.0.2 on 2026-02-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_music_play_count_videocontent_view_count_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='music',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='music/'),
        ),
        migrations.AlterField(
            model_name='music',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
