# Generated by Django 6.0.2 on 2026-02-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_music_audio_url_music_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='duration',
            field=models.IntegerField(help_text='Durations in seconds'),
        ),
    ]
