# Generated by Django 6.0.2 on 2026-02-17 09:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_music_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='music',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
