# Generated by Django 6.0.2 on 2026-02-19 11:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_videocontent_fields_cloudinary'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocontent',
            name='is_public_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='youtube_trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Episode Thumbnail'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Episode Video File'),
        ),
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Audio File'),
        ),
        migrations.AlterField(
            model_name='music',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Album Cover / Thumbnail'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Thumbnail Image'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='trailer_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Trailer Video (Optional)'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Main Video File'),
        ),
    ]
