# Generated by Django 6.0.2 on 2026-02-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_videocontent_is_public_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocontent',
            name='video_url',
        ),
        migrations.AddField(
            model_name='videocontent',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
