# Generated by Django 6.0.2 on 2026-02-19 16:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_remove_videocontent_video_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['season_number', 'episode_number']},
        ),
        migrations.AlterModelOptions(
            name='videocontent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Video Content', 'verbose_name_plural': 'Video Contents'},
        ),
        migrations.AddField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, help_text='Local video file for episode', null=True, upload_to='episodes/'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.IntegerField(help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Episode Video (Cloudinary)'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='is_public_domain',
            field=models.BooleanField(default=False, help_text='True = Play local video file | False = Embed YouTube trailer'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_file',
            field=models.FileField(blank=True, help_text='Local video file for public domain content', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='youtube_trailer_url',
            field=models.URLField(blank=True, help_text='YouTube embed URL (e.g., https://www.youtube.com/embed/VIDEO_ID)', null=True),
        ),
    ]
