# Generated by Django 6.0.2 on 2026-02-26 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_episode_options_alter_videocontent_options_and_more'),
        ('users', '0004_remove_user_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='music',
            name='duration',
            field=models.IntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(condition=models.Q(('video__isnull', False)), fields=('profile', 'video'), name='unique_profile_video'),
        ),
        migrations.AddConstraint(
            model_name='watchlist',
            constraint=models.UniqueConstraint(condition=models.Q(('music__isnull', False)), fields=('profile', 'music'), name='unique_profile_music'),
        ),
    ]
