# Generated by Django 6.0.2 on 2026-03-04 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_add_new_features'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentApproval',
        ),
    ]
