# Generated by Django 6.0.2 on 2026-03-04 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_delete_contentapproval'),
    ]

    operations = [
        # Content rating fields removed - parental controls feature deleted
    ]
