# Generated by Django 6.0.2 on 2026-03-04 09:39

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_episode_content_rating_music_content_rating_and_more'),
        ('users', '0007_remove_parental_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name_plural': 'Music'},
        ),
        migrations.AlterModelOptions(
            name='videocontent',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='videowatchhistory',
            options={'verbose_name_plural': 'Video Watch Histories'},
        ),
        migrations.AlterUniqueTogether(
            name='videowatchhistory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='video_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, help_text='Local video file for public domain episodes', null=True, upload_to='episodes/'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='music',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='music',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='is_public_domain',
            field=models.BooleanField(default=False, help_text='If True, video is stored locally. If False, uses YouTube trailer.'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='trailer_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='youtube_trailer_url',
            field=models.URLField(blank=True, help_text='YouTube embed URL for non-public domain content trailers', null=True),
        ),
        migrations.AlterField(
            model_name='videowatchhistory',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.CreateModel(
            name='ContentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('NEEDS_CHANGES', 'Needs Changes')], default='PENDING', max_length=20)),
                ('submission_notes', models.TextField(blank=True, help_text='Notes from the content uploader')),
                ('review_notes', models.TextField(blank=True, help_text='Feedback from the reviewer')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_history', to='content.videocontent')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_content', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Approval',
                'verbose_name_plural': 'Content Approvals',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
