# Generated by Django 6.0.2 on 2026-03-10 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_music_options_alter_videocontent_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentApproval',
        ),
    ]
