# Generated by Django 6.0.2 on 2026-03-13 15:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_recommendation_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contentsimilarity',
            new_name='content_con_video_a_d9b6ae_idx',
            old_name='content_con_video_a_b8b8c5_idx',
        ),
        migrations.RenameIndex(
            model_name='contentsimilarity',
            new_name='content_con_music_a_27c155_idx',
            old_name='content_con_music_a_b8b8c5_idx',
        ),
        migrations.RenameIndex(
            model_name='musiclistenhistory',
            new_name='content_mus_user_id_36d0eb_idx',
            old_name='content_mus_user_id_b8b8c5_idx',
        ),
        migrations.RenameIndex(
            model_name='musiclistenhistory',
            new_name='content_mus_profile_a3d19f_idx',
            old_name='content_mus_profile_b8b8c5_idx',
        ),
        migrations.RenameIndex(
            model_name='musiclistenhistory',
            new_name='content_mus_music_i_175f01_idx',
            old_name='content_mus_music_id_b8b8c5_idx',
        ),
        migrations.RenameIndex(
            model_name='userinteraction',
            new_name='content_use_user_id_7a0172_idx',
            old_name='content_use_user_id_b8b8c5_idx',
        ),
        migrations.RenameIndex(
            model_name='userinteraction',
            new_name='content_use_profile_29de6c_idx',
            old_name='content_use_profile_b8b8c5_idx',
        ),
        migrations.RenameIndex(
            model_name='userinteraction',
            new_name='content_use_profile_5ebec6_idx',
            old_name='content_use_profile_music_b8b8c5_idx',
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes (auto-filled for local videos, manual for YouTube)', null=True),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='is_public_domain',
            field=models.BooleanField(default=False, help_text='✅ Check for LOCAL video uploads | ❌ Uncheck for YouTube trailers only'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='🖼️ Upload thumbnail image (required for both local and YouTube content)', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_file',
            field=models.FileField(blank=True, help_text='📁 Upload your local video file here (only for public domain content)', null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='youtube_trailer_url',
            field=models.URLField(blank=True, help_text='🎬 YouTube embed URL (format: https://www.youtube.com/embed/VIDEO_ID)', null=True),
        ),
    ]
