# Generated by Django 6.0.2 on 2026-03-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_rename_content_con_video_a_b8b8c5_idx_content_con_video_a_d9b6ae_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='thumbnail',
        ),
    ]
