# Generated by Django 6.0.2 on 2026-03-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_remove_music_thumbnail'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='episode',
            constraint=models.UniqueConstraint(fields=('series', 'season_number', 'episode_number'), name='unique_episode_per_series'),
        ),
    ]
