# Generated by Django 6.0.2 on 2026-03-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_episode_unique_episode_per_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Episode approval status', max_length=20),
        ),
        migrations.AlterField(
            model_name='episode',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
