# Generated by Django 6.0.2 on 2026-03-25 09:05

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_add_episode_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='☁️ Upload episode video file — stored directly on Cloudinary', max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='is_public_domain',
            field=models.BooleanField(default=False, help_text='✅ Check for Cloudinary video uploads | ❌ Uncheck for YouTube trailers only'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_file',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='☁️ Upload video file — stored directly on Cloudinary', max_length=255, null=True, verbose_name='video'),
        ),
    ]
