# Generated by Django 6.0.2 on 2026-03-25 09:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_alter_episode_video_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='video_file',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='is_public_domain',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='video_file',
        ),
        migrations.AlterField(
            model_name='episode',
            name='video_url',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='☁️ Upload episode video — stored on Cloudinary', max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='thumbnail',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='🖼️ Upload thumbnail image', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_url',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='☁️ Upload video file — stored on Cloudinary', max_length=255, null=True, verbose_name='video'),
        ),
    ]
