# Generated by Django 5.2.7 on 2026-04-01 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_merge_watch_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videowatchhistory',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='videowatchhistory',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='videowatchhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videowatchhistory',
            name='video',
        ),
        migrations.RemoveIndex(
            model_name='musiclistenhistory',
            name='content_mus_user_id_36d0eb_idx',
        ),
        migrations.RemoveIndex(
            model_name='musiclistenhistory',
            name='content_mus_profile_a3d19f_idx',
        ),
        migrations.RemoveIndex(
            model_name='musiclistenhistory',
            name='content_mus_music_i_175f01_idx',
        ),
        migrations.AlterField(
            model_name='contentsimilarity',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='musiclistenhistory',
            name='duration_listened',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='musiclistenhistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='musiclistenhistory',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_listen_history', to='content.music'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userinteraction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='VideoWatchHistory',
        ),
    ]
