# Generated by Django 6.0.2 on 2026-02-23 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('PROFILE_CREATED', 'Profile Created'), ('PASSWORD_RESET', 'Password Reset'), ('VIDEO_UPLOADED', 'Video Uploaded'), ('EPISODE_ADDED', 'Episode Added'), ('MUSIC_UPLOADED', 'Music Uploaded'), ('CONTENT_DELETED', 'Content Deleted'), ('CONTENT_UPDATED', 'Content Updated'), ('SUBSCRIPTION_PURCHASED', 'Subscription Purchased'), ('SUBSCRIPTION_CANCELLED', 'Subscription Cancelled'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('FEEDBACK_SUBMITTED', 'Feedback Submitted'), ('CONTACT_MESSAGE', 'Contact Message'), ('ADMIN_LOGIN', 'Admin Login'), ('CONTENT_MODERATED', 'Content Moderated')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
