# Generated by Django 6.0.2 on 2026-02-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_alter_activitylog_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('USER_REGISTERED', 'User Registered'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('PROFILE_CREATED', 'Profile Created'), ('PASSWORD_RESET', 'Password Reset'), ('VIDEO_UPLOADED', 'Video Uploaded'), ('EPISODE_ADDED', 'Episode Added'), ('MUSIC_UPLOADED', 'Music Uploaded'), ('CONTENT_DELETED', 'Content Deleted'), ('CONTENT_UPDATED', 'Content Updated'), ('SUBSCRIPTION_PURCHASED', 'Subscription Purchased'), ('SUBSCRIPTION_CANCELLED', 'Subscription Cancelled'), ('PAYMENT_SUCCESS', 'Payment Success'), ('PAYMENT_FAILED', 'Payment Failed'), ('FEEDBACK_SUBMITTED', 'Feedback Submitted'), ('FEEDBACK_UPDATED', 'Feedback Updated'), ('FEEDBACK_RESOLVED', 'Feedback Resolved'), ('ADMIN_LOGIN', 'Admin Login'), ('CONTENT_MODERATED', 'Content Moderated')], max_length=50),
        ),
    ]
